spring:
  datasource:
    url: jdbc:postgresql://localhost/praise_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    generate-ddl: true
    properties:
      hibernate.enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update