# --------------------------------------- COMMON PROPERTIES ---------------------------------------
server:
  port: 8088

# --------------------------------------- SPRING PROPERTIES ---------------------------------------
spring:
  # ------------------------------------- DATASOURCE PROPERTIES -------------------------------------
  config:
    import:
#      - classpath:db/local/h2_db.properties
      - classpath:db/local/postgres_db.yaml
  cache:
    cache-names:
      - buckets
    caffeine:
      spec: maximumSize=1000000,expireAfterAccess=3600s
#  quartz:
#    job-store-type: jdbc
#    jdbc:
#      initialize-schema: never
#    properties:
#      org.quartz.threadPool.threadCount: 5
# ------------------------------------ PRAISESYSTEM PROPERTIES -------------------------------------
praise-system:
  admin-addresses:
    - "0xc19AbEBaa5BeEE7eE2b20ee990eC63f02B0A0D0c" # JUST ADD YOUR METAMASK ADDRESS HERE
    - "0xc19AbEBaa5BeEE7eE2b20ee990eC63f02B0A0D11"
    - "0xc19AbEBaa5BeEE7eE2b20ee990eC63f02B0A0D22"
  frontend-url: "http://localhost:3000"
# ---------------------------------------- JWT PROPERTIES -----------------------------------------
jwt:
  token:
    secret: somesecret
    expirationTimeMS: 2629800000
# ------------------------------------ RATE-LIMIT PROPERTIES --------------------------------------
springdoc:
  swagger-ui:
    operationsSorter: alpha
  model-converters:
    pageable-converter:
      enabled: true
bucket4j:
  enabled: true
  filters:
    - cache-name: buckets
      url: /*
      rate-limits:
        - bandwidths:
            - capacity: 5
              time: 1
              unit: minutes
              fixed-refill-interval: 1
              fixed-refill-interval-unit: minutes

# -------------------------------------- OPENFEIGN PROPERTIES -------------------------------------


# ------------------------------------- SCHEDULERS PROPERTIES -------------------------------------
